# Generated by Django 2.2.10 on 2023-05-08 20:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=32, null=True, verbose_name='招生年份')),
                ('school', models.CharField(max_length=32, null=True, verbose_name='院校名称')),
                ('department', models.CharField(max_length=32, null=True, verbose_name='院系')),
                ('code', models.CharField(max_length=32, null=True, verbose_name='专业代码')),
                ('name', models.CharField(max_length=32, null=True, verbose_name='专业名称')),
                ('count', models.IntegerField(null=True, verbose_name='报考人数')),
                ('record', models.IntegerField(null=True, verbose_name='录取人数')),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='报录比')),
            ],
            options={
                'verbose_name': '报录比',
                'verbose_name_plural': '报录比',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True, verbose_name='院校名称')),
                ('location', models.CharField(max_length=32, null=True, verbose_name='所在地')),
                ('department', models.CharField(max_length=32, null=True, verbose_name='院校隶属')),
                ('is_research', models.BooleanField(choices=[(1, '研究生院'), (0, ' ')], max_length=32, null=True, verbose_name='是否有研究生院')),
                ('is_auto_line', models.BooleanField(choices=[(1, '自划线'), (0, ' ')], max_length=32, null=True, verbose_name='是否为自划线院校')),
                ('is_double_one', models.BooleanField(choices=[(1, '双一流'), (0, ' ')], max_length=32, null=True, verbose_name='是否为双一流院校')),
                ('icon', models.CharField(default='', max_length=255, verbose_name='图标链接')),
                ('url', models.CharField(default='', max_length=255, verbose_name='院校链接')),
            ],
            options={
                'verbose_name': '院校',
                'verbose_name_plural': '院校',
            },
        ),
        migrations.CreateModel(
            name='ScoreLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=32, null=True, verbose_name='招生年份')),
                ('school', models.CharField(max_length=32, null=True, verbose_name='院校名称')),
                ('department', models.CharField(max_length=64, null=True, verbose_name='院系')),
                ('code', models.CharField(max_length=32, null=True, verbose_name='专业代码')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='专业名称')),
                ('total_score', models.IntegerField(null=True, verbose_name='总分')),
                ('politics', models.IntegerField(null=True, verbose_name='政治')),
                ('english', models.IntegerField(null=True, verbose_name='外语')),
                ('subject_three', models.IntegerField(null=True, verbose_name='科目三')),
                ('subject_four', models.IntegerField(null=True, verbose_name='科目四')),
            ],
            options={
                'verbose_name': '分数线',
                'verbose_name_plural': '分数线',
            },
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, null=True, verbose_name='专业代码')),
                ('name', models.CharField(max_length=32, null=True, verbose_name='专业名称')),
                ('subject', models.CharField(max_length=32, null=True, verbose_name='所属学科门类')),
                ('first_subject', models.CharField(max_length=32, null=True, verbose_name='所属一级学科')),
                ('type', models.CharField(max_length=32, null=True, verbose_name='专业类型')),
            ],
            options={
                'verbose_name': '专业',
                'verbose_name_plural': '专业',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, null=True, unique=True, verbose_name='账号')),
                ('password', models.CharField(max_length=255, null=True, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='邮箱')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0, verbose_name='评分')),
                ('score_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='评分时间')),
                ('school', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='schoolscores', to='app01.School', verbose_name='学校')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='userscores', to='app01.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户评分',
                'verbose_name_plural': '用户评分',
            },
        ),
        migrations.CreateModel(
            name='UserCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.BooleanField(choices=[(0, '点击收藏'), (1, '取消收藏')], default=False, verbose_name='用户收藏')),
                ('collection_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='收藏时间')),
                ('school', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='schoolcollections', to='app01.School', verbose_name='学校')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercollections', to='app01.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户收藏',
                'verbose_name_plural': '用户收藏',
            },
        ),
    ]
