# Generated by Django 2.2.10 on 2023-05-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_province',
            field=models.CharField(choices=[('anhui', '安徽'), ('beijing', '北京'), ('chongqing', '重庆'), ('fujian', '福建'), ('gansu', '甘肃'), ('guangdong', '广东'), ('guangxi', '广西'), ('guizhou', '贵州'), ('hainan', '海南'), ('hebei', '河北'), ('heilongjiang', '黑龙江'), ('henan', '河南'), ('hubei', '湖北'), ('hunan', '湖南'), ('jiangsu', '江苏'), ('jiangxi', '江西'), ('jilin', '吉林'), ('liaoning', '辽宁'), ('neimenggu', '内蒙古'), ('ningxia', '宁夏'), ('qinghai', '青海'), ('shandong', '山东'), ('shanxi', '山西'), ('shanxi1', '陕西'), ('shanghai', '上海'), ('sichuan', '四川'), ('tianjin', '天津'), ('xinjiang', '新疆'), ('xizang', '西藏'), ('yunnan', '云南'), ('zhejiang', '浙江')], max_length=255, null=True, verbose_name='用户意向地区'),
        ),
    ]
